version: '2'
services:
  app:
    container_name: app
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./dockerfile
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/triple
      - SPRING_DATASOURCE_USERNAME=joon
      - SPRING_DATASOURCE_PASSWORD=3621
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=joon
      - POSTGRES_DB=triple
      - POSTGRES_PASSWORD=3621
