drop table if exists mileage;
drop table if exists mileage_history;

create table mileage
(
    id                 bigint generated by default as identity
        primary key,
    attached_photo_cnt integer      not null,
    content_length     integer      not null,
    created_at         timestamp    not null,
    deleted            boolean      not null,
    deleted_at         timestamp,
    mileage_id         varchar(255) not null,
    place_id           varchar(255) not null,
    point              integer      not null,
    review_id          varchar(255) not null,
    updated_at         timestamp    not null,
    user_id            varchar(255) not null
);

alter table mileage
    owner to joon;

create index place_index
    on mileage (place_id);

create index place_review_user_index
    on mileage (place_id, review_id, user_id);

create table mileage_history
(
    id                 bigint generated by default as identity
        primary key,
    attached_photo_cnt integer      not null,
    content_length     integer      not null,
    created_at         timestamp    not null,
    user_current_point integer      not null,
    description        varchar(255) not null,
    mileage_id         varchar(255) not null,
    place_id           varchar(255) not null,
    point              integer      not null,
    review_id          varchar(255) not null,
    state              varchar(255) not null,
    user_id            varchar(255) not null
);

alter table mileage_history
    owner to joon;

create index user_id_index
    on mileage_history (user_id);

create index user_id_place_id_review_id_index
    on mileage_history (user_id, place_id, review_id);



